---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-core
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./core
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-core
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./controllers
  prune: true
  wait: true
  patches:
    # - patch: |-
    #     apiVersion: helm.toolkit.fluxcd.io/v2
    #     kind: HelmRelease
    #     metadata:
    #       name: nfs-provisioner
    #       namespace: nfs-provisioner
    #     spec:
    #       values:
    #         nfs:
    #           path: /volume1/homelab-nfs
    #   target:
    #     kind: HelmRelease
    #     name: nfs-provisioner
    #     namespace: nfs-provisioner
    - patch: |-
        - op: replace
          path: /spec/values/nfs/path
          value: /volume1/homelab-nfs
      target:
        kind: HelmRelease
        name: nfs-provisioner
        namespace: nfs-provisioner
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: ExternalArtifact
    name: infrastructure
  path: ./configs
  prune: true
  patches:
    - patch: |-
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default-pool
          namespace: metallb-system
        spec:
          addresses:
            - 192.168.0.211/32
            - 192.168.0.212/32
      target:
        kind: IPAddressPool
        name: default-pool
        namespace: metallb-system
