---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: ">= 0.15"
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
  values:
    speaker:
      frr:
        enabled: false
