---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  labels:
    toolkit.fluxcd.io/tenant: core
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: cilium
      version: "1.18.6"
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 15m
  values:
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    nodePort:
      enabled: true
    # ingressController:
    #   enabled: true
    #   default: true
    #   loadbalancerMode: shared
    #   defaultSecretNamespace: cert-manager
    #   defaultSecretName: wildcard
    #   service:
    #     annotations:
    #       metallb.io/loadBalancerIPs: 10.0.101.254
    gatewayAPI:
      enableAlpn: true
      enableAppProtocol: true
      enabled: true
    encryption:
      enabled: true
      type: wireguard
    ipam:
      mode: kubernetes
    kubeProxyReplacement: false
    securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: kps
    # dashboards:
    #   enabled: true
    #   annotations:
    #     grafana_folder: Cilium
    envoy:
      # resources:
      #   limits:
      #     memory: 128Mi
      #   requests:
      #     memory: 128Mi
      prometheus:
        serviceMonitor:
          enabled: true
          labels:
            release: kps
    operator:
      replicas: 1
      # resources:
      #   limits:
      #     memory: 256Mi
      #   requests:
      #     memory: 256Mi
      # prometheus:
      #   serviceMonitor:
      #     enabled: true
      #     labels:
      #       release: kps
      # dashboards:
      #   enabled: true
      #   annotations:
      #     grafana_folder: Cilium