---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  labels:
    toolkit.fluxcd.io/tenant: core
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: cilium
      version: "1.18.6"
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 15m
  values:
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    nodePort:
      enabled: true
    gatewayAPI:
      enableAlpn: true
      enableAppProtocol: true
      enabled: true
    ipam:
      mode: kubernetes
    kubeProxyReplacement: false
    securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE

  
