---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    toolkit.fluxcd.io/tenant: core
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 15m
  timeout: 5m
  dependsOn:
    - name: cilium
      namespace: cilium
  chart:
    spec:
      chart: external-secrets
      version: "1.3.*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 15m
  values:
    bitwarden-sdk-server:
      enabled: true
